require 'osx/cocoa'

class GokoRapper
	WINDOW_X = 18
	WINDOW_Y = 26
	WINDOW_OUTER_WIDTH = 1181
	WINDOW_OUTER_HEIGHT = 712
	WINDOW_INNER_WIDTH = 1181
	WINDOW_INNER_HEIGHT = 640

	CANVAS_X = WINDOW_X + (WINDOW_INNER_WIDTH - WINDOW_INNER_HEIGHT * 3 / 2) / 2
	CANVAS_Y = WINDOW_Y + WINDOW_OUTER_HEIGHT - WINDOW_INNER_HEIGHT
	CANVAS_WIDTH = WINDOW_INNER_HEIGHT * 3 / 2
	CANVAS_HEIGHT = WINDOW_INNER_HEIGHT

	GOKO_WIDTH = 1920
	GOKO_HEIGHT = 1280
	ESTATE_X = 286
	ESTATE_Y = 450
	VICTORY_DISRANCE = 160
	SUPPLY_X = 570
	SUPPLY_Y = 218
	SUPPLY_DISTANCE_X = 281
	SUPPLY_DISTANCE_Y = 241
	CURSE_X = 1882
	CURSE_Y = 609
	MONEY_DISTANCE = 157

	#番号と位置の関係は
	# 01234
	# 56789
	def pointSupply(num)
		x = (num % 5) * SUPPLY_DISTANCE_X * CANVAS_WIDTH / GOKO_WIDTH + SUPPLY_X * CANVAS_WIDTH / GOKO_WIDTH + CANVAS_X
		y = (num / 5) * SUPPLY_DISTANCE_Y * CANVAS_HEIGHT / GOKO_HEIGHT + SUPPLY_Y * CANVAS_HEIGHT / GOKO_HEIGHT + CANVAS_Y
		move_mouse(x,y)
	end

	#銅貨とかをポイント
	def pointBasicCard(id)
		
	end

	def move_mouse(x, y)
   		OSX::CGWarpMouseCursorPosition(OSX::CGPointMake(x, y))
 	end
end

r = GokoRapper.new
r.pointSupply(9)
